name: Deploy FastAPI Application to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Create SNS Topic if not exists
        run: |
          source venv/bin/activate
          python create_topic.py your-topic-name

      - name: Package Application
        run: |
          source venv/bin/activate
          cd app
          zip -r9 ../deployment_package.zip .
          echo "Packaged application to deployment_package.zip"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to AWS S3
        run: aws s3 cp deployment_package.zip s3://your-s3-bucket-name/deployment_package.zip

      - name: Deploy Lambda Function
        run: |
          if aws lambda get-function --function-name your-lambda-function-name 2>&1 | grep -q 'ResourceNotFoundException'
          then
            echo "Function does not exist, creating..."
            aws lambda create-function --function-name your-lambda-function-name \
              --runtime python3.8 --role lambda-role-arn \
              --handler your-handler --zip-file fileb://deployment_package.zip \
              --environment Variables="{VAR1='value1',VAR2='value2'}"
          else
            echo "Function exists, updating..."
            aws lambda update-function-code --function-name your-lambda-function-name \
              --zip-file fileb://deployment_package.zip
          fi